// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfOg36NvjYcJ5y9iYWWseDZl1jWVFoYec',
    appId: '1:303101307496:web:89b418b2e1cc6bd18fe9dd',
    messagingSenderId: '303101307496',
    projectId: 'fluttertodoapp-26a9e',
    authDomain: 'fluttertodoapp-26a9e.firebaseapp.com',
    storageBucket: 'fluttertodoapp-26a9e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2UlU0p6xIAQPruiV7GuOsza0psZTBMgc',
    appId: '1:303101307496:android:323801a8937329588fe9dd',
    messagingSenderId: '303101307496',
    projectId: 'fluttertodoapp-26a9e',
    storageBucket: 'fluttertodoapp-26a9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj-lrsb_yQb-jdYIyTIxCpSPshU3BXNGY',
    appId: '1:303101307496:ios:045980f53b24d1638fe9dd',
    messagingSenderId: '303101307496',
    projectId: 'fluttertodoapp-26a9e',
    storageBucket: 'fluttertodoapp-26a9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj-lrsb_yQb-jdYIyTIxCpSPshU3BXNGY',
    appId: '1:303101307496:ios:045980f53b24d1638fe9dd',
    messagingSenderId: '303101307496',
    projectId: 'fluttertodoapp-26a9e',
    storageBucket: 'fluttertodoapp-26a9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfOg36NvjYcJ5y9iYWWseDZl1jWVFoYec',
    appId: '1:303101307496:web:edb76bcd2195100d8fe9dd',
    messagingSenderId: '303101307496',
    projectId: 'fluttertodoapp-26a9e',
    authDomain: 'fluttertodoapp-26a9e.firebaseapp.com',
    storageBucket: 'fluttertodoapp-26a9e.firebasestorage.app',
  );
}
